### ISSUE TITLE
add dependency graph on sentences

### ISSUE THREAD

**Issue by mgogoulos** [eellak/text-analysis#12]
a more light way as displaCy does it would also be beneficial on the sentences section

**Comment by giannisdaras** [comment]
Working on it. We can use displaCy itself for that reason.
displaCy outputs html markup but it's too slow to run on the whole corpus at once.
I am working on a visualize it button next to each sentence which on click redirects to a visualization page for the sentence.

**Comment by giannisdaras** [comment]
Done
