### ISSUE TITLE
Include a back-to-top button on scrolling down

### ISSUE THREAD

**Issue by rbhatia46** [eellak/text-analysis#16]
On scrolling the website, a back-to-top button can be included in the bottom-right corner to make it easier to navigate back to the top.
Please let me know if you need any help with this or if I can integrate this in the existing UI.

**Comment by giannisdaras** [comment]
Thanks for your comment :star:
It is true that a back-to-top button would be extremely useful.
We are planning a lot of UI changes actually, so help is really appreciated.
If you could implement the back-to-top button it would be a very nice addition and I would be more than happy to merge this. If you need any guidance, please let me know :v: .

**Comment by rbhatia46** [comment]
@giannisdaras thanks for your reply! I am onto this issue, and sure I will let you know if I need any guidance! :)

**Comment by mgogoulos** [comment]
Hi @rbhatia46 , thanks for your interest, as @giannisdaras suggests we've been discussing about many UI/UX enhancements and additions that are stepped back due to lack of time. Any contribution is appreciated of course!

**Comment by rbhatia46** [comment]
Hi @mgogoulos, thanks for your reply! I have sent a PR for the same. Please check out #17 @giannisdaras  and I would love to contribute for any other UI/UX enhancements, I would be happy to help! :)

**Comment by giannisdaras** [comment]
Hello @rbhatia46! :smiley: 
Thanks for your work, I tested it and it works great.
There are a lot of UI/UX enhancements that you could work with. You can start with any one of the open issues but if are planning to add/improve something else you could open a new issue and I will be happy to discuss it with you.
I really appreciate your interest! 

Cheers :100: :+1:

**Comment by rbhatia46** [comment]
Thank you so much @giannisdaras. I really find this project interesting, because I am a Web developer and a Deep Learning enthusiast, I have some experience with NLTK, I will check out spaCy for sure to see if I can contribute with the NLP part as well. For now, I think there are no more UI/UX issues open although I was thinking of one big enhancement. Maybe we can convert nlpbuddy into a PWA(Progressive Web App), so that it can reach more number of people, but that would be kind of time-consuming project, along with some more improvements in the NLP part, basically working towards **nlpbuddy v2.0**. I am really excited for this, and was wondering if I can take this up in summers, if you guys are applying for GSoC this year as well, please let me know. 😄
